name: CI Security + Kind Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task4-part1:latest .
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.41.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.41.3_Linux-64bit.deb

      - name: Scan Docker image with Trivy
        run: |
          mkdir -p trivy-report
          trivy image --format template --template "@contrib/html.tpl" \
          --output trivy-report/report.html \
          ${{ secrets.DOCKER_USERNAME }}/task4-part1:latest
          
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task4-part1:latest

      - name: Push Trivy HTML report to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add trivy-report/report.html
          git commit -m "Add Trivy HTML report [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main